**Objectives**

In this lab, we will

1. Know basic use of Pandas.

2. Understand what are re-identification attack, reconstruction attack and differential attack.

3. Understand how to implement these attack methods.

# Basic use of Pandas

## What is Pandas?

**pandas** is a Python package providing fast, flexible, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intuitive. It aims to be the fundamental high-level building block for doing practical, **real world** data analysis in Python. Additionally, it has the broader goal of becoming **the most powerful and flexible open source data analysis / manipulation tool available in any language**. It is already well on its way toward this goal.

## Import Pandas

Importing a library means loading it into the memory and then it’s there for you to work with. In order to import Pandas all you have to do is run the following code:

In [1]:
import pandas as pd # import the Pandas library
import numpy as np

## Constructa dictionary

Example:

    data = {'First Column Name':  ['First value', 'Second value',...],

        'Second Column Name': ['First value', 'Second value',...],
         ....
         }

In [2]:
data = {'Name': ['Alice', 'Betty', 'Charles', 'David', 'Emily', 'Fred'],
       'Zipcode': [47677, 47602, 47678, 47905, 47909, 47906],
       'Age': [29, 22, 27, 43, 42, 47],
       'Sex': ['F', 'F', 'M', 'M', 'F', 'M'],
       'Disease': ['Ovarian Cancer', 'Ovarian Cancer',
                   'Prostate Cancer', 'Flu', 'Heart Disease', 'Heart Disease']}

## Create a dataframe from dictionary

In order to convert a certain Python object (dictionary, lists etc) the basic command is:

    pd.DataFrame()

Two-dimensional size-mutable, potentially heterogeneous tabular data
structure with labeled axes (rows and columns).

In [3]:
df = pd.DataFrame(data)
df

      Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer
3    David    47905   43   M              Flu
4    Emily    47909   42   F    Heart Disease
5     Fred    47906   47   M    Heart Disease

## View and inspect data


1. Get the first n rows

In [4]:
df.head(5)

      Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer
3    David    47905   43   M              Flu
4    Emily    47909   42   F    Heart Disease

2. Get the last n rows

In [5]:
df.tail(3)

    Name  Zipcode  Age Sex        Disease
3  David    47905   43   M            Flu
4  Emily    47909   42   F  Heart Disease
5   Fred    47906   47   M  Heart Disease

3. Ger the number of rows and columns

In [6]:
df.shape

(6, 5)

4. Get the index, datatype and memory information.

In [7]:
df.info

<bound method DataFrame.info of       Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer
3    David    47905   43   M              Flu
4    Emily    47909   42   F    Heart Disease
5     Fred    47906   47   M    Heart Disease>

5. Get the mean of all columns

In [8]:
df.mean(numeric_only=True)

Zipcode    47779.5
Age           35.0
dtype: float64

6. Get the correlation between columns in a data frame

In [9]:
df.corr(numeric_only=True)

          Zipcode       Age
Zipcode  1.000000  0.983538
Age      0.983538  1.000000

7. Get the highest value in each column

In [10]:
df.max()

Name                  Fred
Zipcode              47909
Age                     47
Sex                      M
Disease    Prostate Cancer
dtype: object

## Selection of Data

1. Select columns

In [11]:
df['Sex']

0    F
1    F
2    M
3    M
4    F
5    M
Name: Sex, dtype: object

In [12]:
df[['Age','Sex']]

   Age Sex
0   29   F
1   22   F
2   27   M
3   43   M
4   42   F
5   47   M

2. Select rows by position

In [13]:
df.iloc[0]

Name                Alice
Zipcode             47677
Age                    29
Sex                     F
Disease    Ovarian Cancer
Name: 0, dtype: object

In [14]:
df.iloc[:3]

      Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer

3. Select an element

In [15]:
df.iloc[0,0]

'Alice'

4. Select rows by index

In [16]:
df.loc[0]

Name                Alice
Zipcode             47677
Age                    29
Sex                     F
Disease    Ovarian Cancer
Name: 0, dtype: object

In [17]:
df.loc[:3]

      Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer
3    David    47905   43   M              Flu

In [18]:
df.loc[0,'Name']

'Alice'

5. Replace values with different values

Replace values given in `to_replace` with `value`. Values of the DataFrame are replaced with other values dynamically.

    df.replace(to_replace=None, value=None, inplace=False)

In [19]:
df.replace('Flu','Lung Cancer')

      Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer
3    David    47905   43   M      Lung Cancer
4    Emily    47909   42   F    Heart Disease
5     Fred    47906   47   M    Heart Disease

# Implementation of Re-identification / De-anonymisation

## Linkage Attack

We now create a small dataset and see how to implement a linkage attack. We follow the mini dataset from the former introduction.

In [20]:
data = {'Name': ['Alice', 'Betty', 'Charles', 'David', 'Emily', 'Fred',
'Tom', 'Alex', 'Vincent', 'Serena'],
'Zipcode': [47677, 47602, 47678, 47905, 47909, 47906,
47433,47489,47422,47443],
'Age': [29, 22, 27, 43, 42, 47,
32,33,34,38],
'Sex': ['F', 'F', 'M', 'M', 'F', 'M',
'M', 'M', 'M', 'F'],
'Disease': ['Ovarian Cancer', 'Ovarian Cancer',
'Prostate Cancer', 'Flu', 'Heart Disease', 'Heart Disease',
'Flu', 'Flu', 'Flu', 'Heart Disease']}

In [21]:
df = pd.DataFrame(data)
df

      Name  Zipcode  Age Sex          Disease
0    Alice    47677   29   F   Ovarian Cancer
1    Betty    47602   22   F   Ovarian Cancer
2  Charles    47678   27   M  Prostate Cancer
3    David    47905   43   M              Flu
4    Emily    47909   42   F    Heart Disease
5     Fred    47906   47   M    Heart Disease
6      Tom    47433   32   M              Flu
7     Alex    47489   33   M              Flu
8  Vincent    47422   34   M              Flu
9   Serena    47443   38   F    Heart Disease

Firstly, we remove its key attribute "name",

In [22]:
data1 = {'Zipcode': [47677, 47602, 47678, 47905, 47909, 47906,
47433,47489,47422,47443],
'Age': [29, 22, 27, 43, 42, 47,
32,33,34,38],
'Sex': ['F', 'F', 'M', 'M', 'F', 'M',
'M', 'M', 'M', 'F'],
'Disease': ['Ovarian Cancer', 'Ovarian Cancer',
'Prostate Cancer', 'Flu', 'Heart Disease', 'Heart Disease',
'Flu', 'Flu', 'Flu', 'Heart Disease']}

In [23]:
df1 = pd.DataFrame(data1)
df1

   Zipcode  Age Sex          Disease
0    47677   29   F   Ovarian Cancer
1    47602   22   F   Ovarian Cancer
2    47678   27   M  Prostate Cancer
3    47905   43   M              Flu
4    47909   42   F    Heart Disease
5    47906   47   M    Heart Disease
6    47433   32   M              Flu
7    47489   33   M              Flu
8    47422   34   M              Flu
9    47443   38   F    Heart Disease

Secondly, we remove its sensitive attribute "Disease" as the second dataset

In [24]:
data2 = {'Name': ['Alice', 'Betty', 'Charles', 'David', 'Emily', 'Fred',
'Tom', 'Alex', 'Vincent', 'Serena'],
'Zipcode': [47677, 47602, 47678, 47905, 47909, 47906,
47433,47489,47422,47443],
'Age': [29, 22, 27, 43, 42, 47,
32,33,34,38],
'Sex': ['F', 'F', 'M', 'M', 'F', 'M',
'M', 'M', 'M', 'F']}

In [25]:
df2 = pd.DataFrame(data2)
df2

      Name  Zipcode  Age Sex
0    Alice    47677   29   F
1    Betty    47602   22   F
2  Charles    47678   27   M
3    David    47905   43   M
4    Emily    47909   42   F
5     Fred    47906   47   M
6      Tom    47433   32   M
7     Alex    47489   33   M
8  Vincent    47422   34   M
9   Serena    47443   38   F

So when an adversary has both datasets, the adversary may re-identify that "Alice" and "Betty" have "Ovarian Cancer", "Charies" has "Prostate Cancer", and so on.

## Unsorted Matching Attack

Now, let's create three datasets to see how to implement unsorted matching attack.

In [26]:
data_unsorted1 = {"Sex": ["Female", "Female", "Female", "Female", "Female", "Female", "Male", "Male", "Male", "Male", "Male"],
                  "ZIP": ['02138', '02139', '02141', '02142', '02138', '02139', '02141', '02142', '02138','02139', '02141']}

In [27]:
df3 = pd.DataFrame(data_unsorted1)
df3

       Sex    ZIP
0   Female  02138
1   Female  02139
2   Female  02141
3   Female  02142
4   Female  02138
5   Female  02139
6     Male  02141
7     Male  02142
8     Male  02138
9     Male  02139
10    Male  02141

Now, let's build the second dataset of these three, We anonymise its first attribute "Sex".

In [28]:
data_unsorted2 = {"Sex" : ["Person", "Person", "Person", "Person", "Person", "Person", "Person", "Person", "Person", "Person"],
                  "ZIP" : ['02138', '02139', '02141', '02142', '02138', '02139', '02141', '02141', '02138', '02139']}

In [29]:
df4 = pd.DataFrame(data_unsorted2)
df4

      Sex    ZIP
0  Person  02138
1  Person  02139
2  Person  02141
3  Person  02142
4  Person  02138
5  Person  02139
6  Person  02141
7  Person  02141
8  Person  02138
9  Person  02139

Now, let's build the third dataset of these three. We anonymise its second attribute "ZIP".

In [30]:
data_unsorted3 = {"Sex" : ["Female", "Female", "Female", "Female", "Female", "Female", "Male", "Male", "Male", "Male", "Male", "Male"],
                  "ZIP" : ['02130', '02130', '02140', '02140', '02130', '02130', '02140', '02140', '02130', '02130', '02140', '02140']}

In [31]:
df5 = pd.DataFrame(data_unsorted3)
df5

       Sex    ZIP
0   Female  02130
1   Female  02130
2   Female  02140
3   Female  02140
4   Female  02130
5   Female  02130
6     Male  02140
7     Male  02140
8     Male  02130
9     Male  02130
10    Male  02140
11    Male  02140

In [32]:
data_unsorted4 = {"Sex1" : ["Female", "Female", "Female", "Female", "Female", "Female", "Male"  , "Male"  , "Male"  , "Male"  , "Male"  , "Male"],
                  "ZIP1" : ["02138" , "02139" , "02141" , "02142" , "02138" , "02139" , "02141" , "02142" , "02138" , "02139" , "02141" , "02142"],
                  "Sex2" : ["Person", "Person", "Person", "Person", "Person","Person" , "Person", "Person", "Person", "Person", "Person", "Person"],
                  "ZIP2" : ["02130" , "02130" , "02140" , "02140" , "02130" , "02130" , "02140" , "02140" , "02130" , "02130" , "02140" , "02140"],
                  "Sex3" : ["Female", "Female", "Female", "Female", "Female", "Female", "Male"  , "Male"  , "Male"  , "Male"  , "Male"  , "Male"],
                  "ZIP3" : ["02138" , "02139" , "02141" , "02142" , "02138" , "02139" , "02141" , "02142" , "02138" , "02139" , "02141" , "02142"]}

In [33]:
df6 = pd.DataFrame(data_unsorted4)
df6

      Sex1   ZIP1    Sex2   ZIP2    Sex3   ZIP3
0   Female  02138  Person  02130  Female  02138
1   Female  02139  Person  02130  Female  02139
2   Female  02141  Person  02140  Female  02141
3   Female  02142  Person  02140  Female  02142
4   Female  02138  Person  02130  Female  02138
5   Female  02139  Person  02130  Female  02139
6     Male  02141  Person  02140    Male  02141
7     Male  02142  Person  02140    Male  02142
8     Male  02138  Person  02130    Male  02138
9     Male  02139  Person  02130    Male  02139
10    Male  02141  Person  02140    Male  02141
11    Male  02142  Person  02140    Male  02142

# Differential Attack

Now we will implement differential attack using the example introduced in the lecture. Firstly, we create a raw dataset without any anonymity.

In [34]:
data_da = {"Name" : ["Alice", "Bob", "Chris", "David", "Eric", "Fiona", "Grace"],
           "Grade" : [85  , 62 , 70, 93 , 58, 81 , 74]}

In [35]:
df8 = pd.DataFrame(data_da)
df8

    Name  Grade
0  Alice     85
1    Bob     62
2  Chris     70
3  David     93
4   Eric     58
5  Fiona     81
6  Grace     74

When we consider the attribute 'Grade' is sensitive, the dataset is anonymised as following:

In [36]:
data_da1 = {"Name" : ["Alice", "Bob", "Chris", "David", "Eric", "Fiona", "Grace"],
"Grade" : ["**", "**", "**", "**", "**", "**", "**"]}

In [37]:
df9 = pd.DataFrame(data_da1)
df9

    Name Grade
0  Alice    **
1    Bob    **
2  Chris    **
3  David    **
4   Eric    **
5  Fiona    **
6  Grace    **

However, we can still query about the raw dataset, for example, we want to know the sum of all students' grade, it will return the result to us.

In [38]:
df8['Grade'].sum()

523

We know that the sum of all students' grade is 523. Now, we will query about the sum of the first 6 students' grade except Grace, it will retuern the result to us.

In [39]:
df8['Grade'].sum() - df8['Grade'][6]

449

Now, we can use the first query answer to subtract the second query answer to get Grace's grade

In [40]:
523 - 449

74

It returns Grace's grade is 74.

# Conclusion

In this lab, we learnt:

1. Pandas and DataFrame;

2. How to build a dataframe and show the dataset;

3. Re-identification attack, re-construction attacks and differential attack.